### ISSUE TITLE
License verification for all java source files during build time

### ISSUE THREAD

**Issue by lucian-cm** [CloudSlang/cs-actions#190]
This is related to https://github.com/CloudSlang/cloud-slang/issues/889 which will be fixed soon.
This issue is talking about apply the same solution to `cs-actions`.

**Comment by tethryus** [comment]
License verification added for all Java source files. @lucian-cm do you think that this issue can be closed?

**Comment by tethryus** [comment]
License verification has been added to all the modules. This issue can be closed.
