### ISSUE TITLE
'Check Style' plugin to validate that the code formatting is respecting industry best practices

### ISSUE THREAD

**Issue by lucian-cm** [CloudSlang/cs-actions#191]
So that we can concentrate on important things like application logic during code review when we know this part is automated. 
Just need to apply the solution provided for fix of https://github.com/CloudSlang/cloud-slang/issues/917

**Comment by tethryus** [comment]
Checkstyle plugin has been enabled in the plugin that has been integrated in the build process and the codeclimate engines that have been enabled for current and new integrations.
