### ISSUE TITLE
Amazon AWS EC2

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cs-actions#200]
by @mihaitusa : 

The actual implementation (those 22 op's with J-Clouds) doesn't provide 2 necessary inputs: proxyUsername && proxyPassword. Update them to be as the latest op's that uses AWS QueryApi.

migrated from https://github.com/CloudSlang/cloud-slang/issues/835

**Comment by mihaitusa** [comment]
@Bonczidai Let's all be patient about it. There's only 2 op's that have this problem. One of them (UpdateInstanceType -> ModifyInstanceAttribute) is already on course to be fully rewritten in PR https://github.com/CloudSlang/cs-actions/pull/199.  Remaining just DescribeInstances. @Tirla-Alin should handle it.

**Comment by tethryus** [comment]
Great work @mihaitusa this issue can be closed now, no? Since all the jclouds dependencies have been removed and all the @Actions have been refactored.
