### ISSUE TITLE
Consider remove cs-utilities project

### ISSUE THREAD

**Issue by mihaitusa** [CloudSlang/cs-actions#240]
Consider remove cs-utilities project because has no usage and doesn't bring any value.

**Comment by mihaitusa** [comment]
@chronical @lrevnic Sleep is supported by DSL and probability to use StringEquals as a standalone operation is very low. IMHO cs-utilities brings nothing more than pollution to the cs-actions. WDYT?

**Comment by tethryus** [comment]
@mihaitusa @lrevnic @gituser173 @lucian-cm @chronical We could delete them since they are already used as python scripts as well. Also look on what else can be cleaned up and will not be used in the near future.

**Comment by mihaitusa** [comment]
C'mon guys... burn it down...
