### ISSUE TITLE
PowerShellScriptAction.java should be changed so that returnResult and scriptExitCode are caught in case of exception 

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/cs-actions#296]
When triggering the powershell script .sl files one **can** **easily** end up in a situation like:

> Command failed java.lang.RuntimeException: Slang Error: Error running: 'powershell_script'.
>     Error binding output: 'return_result',
>     Error is: Error in running script expression: 'returnResult',
>     Exception is: Error in running script expression: 'returnResult',
>     Exception is: name 'returnResult' is not defined

The  PowerShellScriptAction.java from cs-powershell needs to be altered to catch such cases and add default returnResult and scriptExitCode values for the user.

_line 158_
>  } catch (NumberFormatException nfe) {
>             resultMap.put(EXCEPTION, ExceptionUtils.getStackTrace(nfe));
>             resultMap.put(RETURN_CODE, RETURN_CODE_FAILURE);
>         } catch (Exception e) {
>             resultMap.put(EXCEPTION, ExceptionUtils.getStackTrace(e));
>             resultMap.put(RETURN_CODE, RETURN_CODE_FAILURE);
>         }
> 

Note: We should also make sure the description of the .sl files mention properly the values of the corner case situations

**Comment by tethryus** [comment]
This issue has been solved in the last PR #376, #375  and #248, which have been reviewed and merged.
