### ISSUE TITLE
GetAccessToken.scala should be moved to /google/actions/authentication folder

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/cs-actions#300]
GetAccessToken.scala is under https://github.com/CloudSlang/cs-actions/tree/master/cs-google/src/main/scala/io/cloudslang/content/google/actions/compute/utils 

I propose we move it under:
https://github.com/CloudSlang/cs-actions/tree/master/cs-google/src/main/scala/io/cloudslang/content/google/actions/authentication folder

**Comment by victorursan** [comment]
see PR #304
