### ISSUE TITLE
It would be nice to add an extra level/spearator for compute based services

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/cs-actions#301]
Example:
google/actions/compute/disks should go under
google/actions/compute/compute_engine/disks

reasoning:
so we can end up to:

google/actions/compute/compute_engine
google/actions/compute/app_engine
google/actions/compute/container_engine
and so on

**Comment by robert-sandor** [comment]
@lrevnic yes, as the actions package contains the actual @Actions, it is used for grouping, so that will remain there

**Comment by andreivasiletruta** [comment]
@lrevnic I originally thought the same and eventually reached @robert-sandor conclusion.

**Comment by victorursan** [comment]
see PR #304
