### ISSUE TITLE
amazon/actions/instances/RunInstancesAction.java did not seem to set instance_type default to m1.small as expected

### ISSUE THREAD

**Issue by shuchihlin** [CloudSlang/cs-actions#308]
"amazon/actions/instances/RunInstancesAction.java" did not seem to set instance_type default to m1.small (if not specified) as expected? Instead, it set to "m1_small" be default which would be rejected by AWS

1. CLI:
cslang>run --f /var/tmp/cslang-cli/content/io/cloudslang/amazon/aws/ec2/instances/run_instances.sl --i identity=xxx,credential=yyy,image_id=ami-31814f58

Operation outputs:
- return_result = <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code...
- return_code = -1

in the execution logs:
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'm1_small' for InstanceType.</Message></Error></Errors><RequestID>c6fea88c-b38f-4f69-964b-07120a8b5606</RequestID></Response>, return_code=-1, exception=, instance_id_result=}, Result: FAILURE, Raw Data: {EXECUTION_ID=101600057, PATH=0, DESCRIPTION=Execution finished running, TIMESTAMP=Thu Jun 22 20:44:53 UTC 2017, STEP_TYPE=OPERATION, STEP_NAME=run_instances, TYPE=EVENT_EXECUTION_FINISHED, RESULT=FAILURE, OUTPUTS={return_result=<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value **'m1_small'** for InstanceType.</Message></Error></Errors><RequestID>c6fea88c-b38f-4f69-964b-07120a8b5606</RequestID></Response>, return_code=-1, exception=, instance_id_result=}}

2. Request was good once we specified "m1.small" as the instance_type input

cslang>run --f /var/tmp/cslang-cli/content/io/cloudslang/amazon/aws/ec2/instances/run_instances.sl --i identity=xxx,credential=yyy,image_id=ami-31814f58,**instance_type=m1.small**

Operation outputs:
- return_result = <?xml version="1.0" encoding="UTF-8"?>
<RunInstancesResponse xmlns="http://ec2.amazonaws.com/doc/...
- instance_id_result = i-0f4c4353a8b194d7d
- return_code = 0
Operation: run_instances finished with result: SUCCESS

**Comment by robert-sandor** [comment]
The issue shoul be fixed once PR #312  is merged.
